### ISSUE TITLE
Homework 3 Feedback 

### ISSUE THREAD

**Issue by Gchism94** [INFO-523-Exercises/hw-03-eshaanmathakari#1]
Dear eshaanmathakari -- Below is the feedback for your assignment. Please review carefully, and stop by office hours if you have any questions about the feedback.

I did not see interpretations for a major portion of the results, your score is **73/100**. Remember that this is for half of the assignment. You received full credit for the other half (the exercise). 

---

### Training and Data: `[10 / 10 points]`

- Reasonable choice for classification: `[6 / 6 points]`
- Narrative: `[4 / 4 points]`
- Feedback: [Insert feedback here.]

### Fitting classification models: `[16 / 22 points]`

  - Correct application: `[16 / 16]`
  - Narrative `[0 / 6]`
  - Feedback: I don't see interpretation on the models here

### Comparing models: `[5 / 10 points]`

  - Correct application: `[5 / 5]`
  - Narrative: `[0 / 5]`
  - Feedback: I don't see and interpretation here

### Applying chosen model: `[5 / 10 points]`

  - Correct application: `[5 / 5]`
  - Narrative: `[0 / 5]`
  - Feedback: I don't see and interpretation here

### Comparing decision boundaries: `[18 / 28 points]`

  - Correct application: `[18 / 18]`
  - Narrative: `[0 / 10]`
  - Feedback: I don't see and interpretation here

### Overall: `[_ / 20 points]`

- `[5 / 5]` - Doesn't require reproduction: .md file is in repo, figures show up in the .md file on GitHub, no egregious errors requiring reproducing the entire analysis to be able to follow it.
- `[3 / 3]` - Code style: Line breaks after `|>` and `+`, spaces around operators, spaces after commas, lines not too long, etc.
- `[3 / 3]` - Code smell: Messy / unnecessarily complex code, difficult to follow, unaddressed warnings, etc.
- `[2 / 3]` - Quality and quantity of commits: No uninformative/nonsense text in commit messages, entire assignment not committed in a single commit.
- **Feedback**: Make your commits more descriptive and commit more often
- `[3 / 3]` - Reasonably sized figures.
- `[3 / 3]` - Font size, organization: No crazy large text for narrative, questions answered in order and identified, easy to follow.

## Late penalty

- [x] On time: No penalty
- [ ] Late, but same day (before midnight): -10 points
- [ ] Late, but next day: -20 points

**Comment by Gchism94** [comment]
You have until 11:59pm to add interpretations to the results that don't have any at this time. You will gain half credit back for these interpretations (total possible score for this half of the total assignment is 87.5/100).

**Comment by eshaanmathakari** [comment]
I have added additional interpretation to the topics mentioned, please let me know if any other changes are to be made, thank you.
